# Auto-generated by fonts/generate_gb2312_font.py
set(GB2312_FONT_SRCS
    "fonts/lv_font_cn_gb2312_16_0.c"
    "fonts/lv_font_cn_gb2312_16_1.c"
    "fonts/lv_font_cn_gb2312_16_2.c"
    "fonts/lv_font_cn_gb2312_16_3.c"
    "fonts/lv_font_cn_gb2312_16_4.c"
    "fonts/lv_font_cn_gb2312_16_5.c"
    "fonts/lv_font_cn_gb2312_16_6.c"
    "fonts/lv_font_cn_gb2312_16_7.c"
)
